name: Automação de Versão e Deploy Docker da API

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  version_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Instalar dependências
        run: npm ci

      - name: Incrementar versão no package.json
        run: npm version patch --no-git-tag-version

      - name: Commitar alterações no package.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add package.json
            git commit -m "chore: release da versão $(node -p "require('./package.json').version")"
            git push
          else
            echo "Nenhuma alteração de versão para commitar."
          fi

      - name: Push das alterações e tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --follow-tags

      - name: Efetuar login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Criar imagem docker
        run: |
          VERSION=$(node -p "require('./package.json').version")
          docker build -t projetointegradorfatec/projeto-cadastro-app-api:latest .
          docker tag projetointegradorfatec/projeto-cadastro-app-api:latest projetointegradorfatec/projeto-cadastro-app-api:$VERSION

      - name: Efetuar push da imagem
        run: |
          VERSION=$(node -p "require('./package.json').version")
          docker push projetointegradorfatec/projeto-cadastro-app-api:$VERSION
          docker push projetointegradorfatec/projeto-cadastro-app-api:latest
